"""Initial migration

Revision ID: 256877920787
Revises: 554b64c11c1d
Create Date: 2025-01-16 12:59:18.536434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256877920787'
down_revision: Union[str, None] = '554b64c11c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_user_slug', table_name='user')
    op.create_unique_constraint(None, 'user', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_slug', 'user', ['slug'], unique=1)
    op.alter_column('user', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
